### ISSUE TITLE
deploy error synology_dsm  Failed to authenticate with error: 102.

### ISSUE THREAD

**Issue by Bigjoke007** [acmesh-official/acme.sh#5184] opened 2024-06-22 22:04 UTC
Steps to reproduce
------------------
export CERT_DOMAIN="nas.bbb.com"
export SYNO_Certificate="nas.bbb.com"
./acme.sh --deploy --home . -d "$CERT_DOMAIN" --deploy-hook synology_dsm --insecure

Debug log
-----------------
./acme.sh --deploy --home . -d "$CERT_DOMAIN" --deploy-hook synology_dsm --insecure --debug 2
[Sat Jun 22 23:57:18 CEST 2024] Lets find script dir.
[Sat Jun 22 23:57:18 CEST 2024] _SCRIPT_='./acme.sh'
[Sat Jun 22 23:57:18 CEST 2024] _script='/usr/local/share/acme.sh/acme.sh'
[Sat Jun 22 23:57:18 CEST 2024] _script_home='/usr/local/share/acme.sh'
[Sat Jun 22 23:57:18 CEST 2024] Using config home:.
[Sat Jun 22 23:57:18 CEST 2024] LE_WORKING_DIR='.'
https://github.com/acmesh-official/acme.sh
v3.0.8
[Sat Jun 22 23:57:18 CEST 2024] Running cmd: deploy
[Sat Jun 22 23:57:18 CEST 2024] Using config home:.
[Sat Jun 22 23:57:18 CEST 2024] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jun 22 23:57:18 CEST 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jun 22 23:57:18 CEST 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sat Jun 22 23:57:18 CEST 2024] _ACME_SERVER_PATH='directory'
[Sat Jun 22 23:57:18 CEST 2024] DOMAIN_PATH='./nas.bbb.com'
[Sat Jun 22 23:57:18 CEST 2024] DOMAIN_CONF='./nas.bbb.com/nas.bbb.com.conf'
[Sat Jun 22 23:57:18 CEST 2024] _deployApi='/usr/local/share/acme.sh/deploy/synology_dsm.sh'
[Sat Jun 22 23:57:18 CEST 2024] _cdomain='nas.bbb.com'
[Sat Jun 22 23:57:19 CEST 2024] SYNO_USE_TEMP_ADMIN
[Sat Jun 22 23:57:19 CEST 2024] SYNO_USE_TEMP_ADMIN='1'
[Sat Jun 22 23:57:19 CEST 2024] Setting temp admin user credential...
[Sat Jun 22 23:57:19 CEST 2024] SYNO_SCHEME='https'
[Sat Jun 22 23:57:19 CEST 2024] SYNO_HOSTNAME='nas.bbb.com'
[Sat Jun 22 23:57:19 CEST 2024] SYNO_PORT='5501'
[Sat Jun 22 23:57:19 CEST 2024] Domain config new key exists, old key SYNO_Certificate='nas.bbb.com' has been removed.
[Sat Jun 22 23:57:19 CEST 2024] SYNO_CERTIFICATE='nas.bbb.com'
[Sat Jun 22 23:57:19 CEST 2024] Getting API version...
[Sat Jun 22 23:57:19 CEST 2024] _base_url='https://nas.bbb.com:5501'
[Sat Jun 22 23:57:19 CEST 2024] GET
[Sat Jun 22 23:57:19 CEST 2024] url='https://nas.bbb.com:5501/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth'
[Sat Jun 22 23:57:19 CEST 2024] timeout=
[Sat Jun 22 23:57:20 CEST 2024] _CURL='curl --silent --dump-header ./http.header  -L  --trace-ascii /tmp/tmp.z0jiea5S9n  -g  --insecure  '
[Sat Jun 22 23:57:21 CEST 2024] ret='0'
[Sat Jun 22 23:57:21 CEST 2024] Logging into nas.bbb.com:5501...
[Sat Jun 22 23:57:21 CEST 2024] SYNO_LOCAL_HOSTNAME
[Sat Jun 22 23:57:21 CEST 2024] Creating temp admin user in Synology DSM...
grep: warning: stray \ before -
grep: warning: stray \ before -
[Sat Jun 22 23:57:27 CEST 2024] GET
[Sat Jun 22 23:57:27 CEST 2024] url='https://nas.bbb.com:5501/webapi/entry.cgi?api=SYNO.API.Auth&version=6&method=login&format=sid&account=sc-acmesh-tmp&passwd=JIwBeSN2H2FKP20D&enable_syno_token=yes'
[Sat Jun 22 23:57:27 CEST 2024] timeout=
[Sat Jun 22 23:57:27 CEST 2024] _CURL='curl --silent --dump-header ./http.header  -L  --trace-ascii /tmp/tmp.lBOv5qlCVC  -g  --insecure  '
[Sat Jun 22 23:57:28 CEST 2024] ret='0'
[Sat Jun 22 23:57:28 CEST 2024] error_code='102'
[Sat Jun 22 23:57:28 CEST 2024] Failed to authenticate with error: 102.
[Sat Jun 22 23:57:28 CEST 2024] Cleanuping temp admin info...
[Sat Jun 22 23:57:31 CEST 2024] Error deploy for domain:nas.bbb.com
[Sat Jun 22 23:57:31 CEST 2024] Deploy error.
```
acme.sh  --issue .....   --debug 2
```
Seems that 'https://nas.bbb.com:5501/webapi/entry.cgi?api=SYNO.API.Auth&version=6&method=login&format=sid&account=sc-acmesh-tmp&passwd=JIwBeSN2H2FKP20D&enable_syno_token=yes' isn't working anymore on DSM6 ?

**Comment by Bigjoke007** [comment] 2024-06-22 22:43
This is already the latest version and the log is already provided.

**Comment by 3ntranced** [comment] 2024-07-01 12:13
i am experiencing exact same issue with same log

**Comment by scruel** [comment] 2024-07-04 08:26
pls provide the log with `--debug 3`

**Comment by webcusp** [comment] 2024-07-05 01:46
./acme.sh --deploy --home . -d <hidden_site> --deploy-hook synology_dsm --ecc --debug 3
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:_exists:534                    readlink exists=0
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:_exists:534                    dirname exists=0
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:__initHome:2665                Lets find script dir.
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:__initHome:2666                _SCRIPT_='./acme.sh'
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:__initHome:2668                _script='/usr/local/share/acme.sh/acme.sh'
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:__initHome:2670                _script_home='/usr/local/share/acme.sh'
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:__initHome:2697                Using config home:.
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:__initHome:2711                ACCOUNT_CONF_PATH='./account.conf'
[Fri Jul  5 13:43:03 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2331                   6:AUTO_UPGRADE='1'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_process:7889                  LE_WORKING_DIR='.'
https://github.com/acmesh-official/acme.sh
v3.0.8
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_process:7897                  Running cmd: deploy
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:__initHome:2697                Using config home:.
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:__initHome:2711                ACCOUNT_CONF_PATH='./account.conf'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_initpath:2827                 default_acme_server
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_initpath:2836                 ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_initpath:2838                 _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_initpath:2841                 _ACME_SERVER_PATH='v2/DV90'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_initpath:2848                 CA_CONF='./ca/acme.zerossl.com/v2/DV90/ca.conf'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_initpath:2925                 DOMAIN_PATH='./<hidden_site>_ecc'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:deploy:5817                    DOMAIN_CONF='./<hidden_site>_ecc/<hidden_site>.conf'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2331                   21:Le_DeployHook='synology_dsm,'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_deploy:5773                   _deployApi='/usr/local/share/acme.sh/deploy/synology_dsm.sh'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    synology_dsm_deploy exists=0
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:56 _cdomain='abifemfit.bioeng.auckland.ac.nz'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:69 SYNO_USE_TEMP_ADMIN
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:72 SYNO_USE_TEMP_ADMIN
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:91 SYNO_USERNAME='admin'
[Fri Jul  5 13:43:04 NZST 2024] SYNO_PASSWORD='[hidden](please add '--output-insecure' to see this value)'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:93 SYNO_DEVICE_NAME
[Fri Jul  5 13:43:04 NZST 2024] SYNO_DEVICE_ID='[hidden](please add '--output-insecure' to see this value)'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2331                   22:SAVED_SYNO_SCHEME='http'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2331                   23:SAVED_SYNO_HOSTNAME='localhost'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_setopt:2331                   24:SAVED_SYNO_PORT='5000'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:118 SYNO_SCHEME='http'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:119 SYNO_HOSTNAME='localhost'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:120 SYNO_PORT='5000'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:126 SYNO_CERTIFICATE
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:134 Getting API version...
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:136 _base_url='http://localhost:5000'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2041                      GET
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2045                      url='http://localhost:5000/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2046                      timeout=
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    curl exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    mktemp exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    wget exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2058                      _CURL='curl --silent --dump-header ./http.header  -L  --trace-ascii /tmp/tmp.ABPEm31PgU  -g  --insecure  '
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2110                      ret='0'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:140 response='{"data":{"SYNO.API.Auth":{"maxVersion":6,"minVersion":1,"path":"auth.cgi"}},"success":true}'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:141 api_path='auth.cgi'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:142 api_version='6'
[Fri Jul  5 13:43:04 NZST 2024] Logging into localhost:5000...
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    od exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_url_encode:678                _url_encode
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_url_encode:679                _hex_str=' 61 64 6d 69 6e'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    od exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_url_encode:678                _url_encode
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_url_encode:679                _hex_str=' 78 32 61 50 35 58'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2041                      GET
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2045                      url='http://localhost:5000/webapi/entry.cgi?api=SYNO.API.Auth&version=6&method=login&format=sid&account=admin&passwd=<hidden>&enable_syno_token=yes'
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2046                      timeout=
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    curl exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    mktemp exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_exists:534                    wget exists=0
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2058                      _CURL='curl --silent --dump-header ./http.header  -L  --trace-ascii /tmp/tmp.6BkfKl8zOB  -g  --insecure  '
[Fri Jul  5 13:43:04 NZST 2024] ./acme.sh:_get:2110                      ret='0'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:226 response='{"error":{"code":102},"success":false}'
[Fri Jul  5 13:43:04 NZST 2024] deploy/synology_dsm.sh:synology_dsm_deploy:231 error_code='102'
[Fri Jul  5 13:43:04 NZST 2024] Failed to authenticate with error: 102.
[Fri Jul  5 13:43:04 NZST 2024] Error deploy for domain:abifemfit.bioeng.auckland.ac.nz
[Fri Jul  5 13:43:04 NZST 2024] Deploy error.

**Comment by scruel** [comment] 2024-07-05 03:50
What is the version of your DSM system? According to the official doc of Login Web API, `102` means "The requested API does not exist."

**Comment by webcusp** [comment] 2024-07-05 03:55
Thanks for your reply. I'm using DSM 6.2.4-25556 Update 7. How can I check if the API is installed? If it's not installed, where can I find and install it?

**Comment by scruel** [comment] 2024-07-05 03:58
@webcusp Use your browser to check if the following URL can be used to authorize (replace user/passwd):
http://localhost:5000/webapi/auth.cgi?api=SYNO.API.Auth&version=6&method=login&format=sid&account=admin&passwd=&enable_syno_token=yes

**Comment by webcusp** [comment] 2024-07-05 04:01
Response: {"error":{"code":400},"success":false}

**Comment by scruel** [comment] 2024-07-05 04:04
@webcusp Replace your synology_dsm.sh file to:
https://github.com/acmesh-official/acme.sh/blob/e711e727194e0ab8d7ca30360e3cf52f50d8e9d7/deploy/synology_dsm.sh
Then retry.

**Comment by webcusp** [comment] 2024-07-05 04:07
Load file /usr/local/share/acme.sh/deploy/synology_dsm.sh error. Please check your api file and try again.

**Comment by scruel** [comment] 2024-07-05 04:10
> Load file /usr/local/share/acme.sh/deploy/synology_dsm.sh error. Please check your api file and try again.

You're not substituting correctly, if you don't know how to do, you can wait feedback from others and wait the PR to be merged.

**Comment by webcusp** [comment] 2024-07-05 04:14
Are you referring to updating a local repo with changes from GitHub repo?

**Comment by scruel** [comment] 2024-07-05 04:16
curl https://raw.githubusercontent.com/acmesh-official/acme.sh/e711e727194e0ab8d7ca30360e3cf52f50d8e9d7/deploy/synology_dsm.sh --output /usr/local/share/acme.sh/deploy/synology_dsm.sh

**Comment by webcusp** [comment] 2024-07-05 04:19
Ah. I did it this way, 
   88  cd /usr/local/share/acme.sh/
   89  ls -ltr
   90  cd deploy/
   91  ls -ltr
   92  mv synology_dsm.sh synology_dsm.sh-bak
   93  wget https://github.com/acmesh-official/acme.sh/blob/e711e727194e0ab8d7ca30360e3cf52f50d8e9d7/deploy/synology_dsm.sh

**Comment by webcusp** [comment] 2024-07-05 04:23
./acme.sh --deploy --home . -d <hidden> --deploy-hook synology_dsm --ecc --debug 3
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:_exists:534                    readlink exists=0
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:_exists:534                    dirname exists=0
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:__initHome:2665                Lets find script dir.
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:__initHome:2666                _SCRIPT_='./acme.sh'
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:__initHome:2668                _script='/usr/local/share/acme.sh/acme.sh'
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:__initHome:2670                _script_home='/usr/local/share/acme.sh'
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:__initHome:2697                Using config home:.
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:__initHome:2711                ACCOUNT_CONF_PATH='./account.conf'
[Fri Jul  5 16:21:08 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_setopt:2331                   6:AUTO_UPGRADE='1'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_process:7889                  LE_WORKING_DIR='.'
https://github.com/acmesh-official/acme.sh
v3.0.8
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_process:7897                  Running cmd: deploy
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:__initHome:2697                Using config home:.
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:__initHome:2711                ACCOUNT_CONF_PATH='./account.conf'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_initpath:2827                 default_acme_server
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_initpath:2836                 ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_initpath:2838                 _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_initpath:2841                 _ACME_SERVER_PATH='v2/DV90'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_initpath:2848                 CA_CONF='./ca/acme.zerossl.com/v2/DV90/ca.conf'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_initpath:2925                 DOMAIN_PATH='./<hidden>_ecc'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:deploy:5817                    DOMAIN_CONF='./<hidden>_ecc/<hidden>.conf'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_setopt:2307                   OK
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_setopt:2331                   21:Le_DeployHook='synology_dsm,'
[Fri Jul  5 16:21:09 NZST 2024] ./acme.sh:_deploy:5773                   _deployApi='/usr/local/share/acme.sh/deploy/synology_dsm.sh'
/usr/local/share/acme.sh/deploy/synology_dsm.sh: line 7: syntax error near unexpected token `newline'
/usr/local/share/acme.sh/deploy/synology_dsm.sh: line 7: `<!DOCTYPE html>'
[Fri Jul  5 16:21:09 NZST 2024] Load file /usr/local/share/acme.sh/deploy/synology_dsm.sh error. Please check your api file and try again.
[Fri Jul  5 16:21:09 NZST 2024] Deploy error.

**Comment by scruel** [comment] 2024-07-05 04:24
> Ah. I did it this way, 88 cd /usr/local/share/acme.sh/ 89 ls -ltr 90 cd deploy/ 91 ls -ltr 92 mv synology_dsm.sh synology_dsm.sh-bak 93 wget https://github.com/acmesh-official/acme.sh/blob/e711e727194e0ab8d7ca30360e3cf52f50d8e9d7/deploy/synology_dsm.sh

You fetched the whole github html page, rather than the source file...

**Comment by webcusp** [comment] 2024-07-05 04:32
My bad. I'm hitting "Unable to update certificate, got error response: {"error":{"code":5598},"success":false}." Is this an error on my side? Wondering.

**Comment by scruel** [comment] 2024-07-05 04:41
> My bad. I'm hitting "Unable to update certificate, got error response: {"error":{"code":5598},"success":false}." Is this an error on my side? Wondering.

It's a related issue, you should search related issues or google it or file a new issue if you still can't resolve it.
May check: https://dr-b.io/post/Synology-DSM-7-with-Lets-Encrypt-and-DNS-Challenge

**Comment by xd1gital** [comment] 2024-08-07 04:02
> My bad. I'm hitting "Unable to update certificate, got error response: {"error":{"code":5598},"success":false}." Is this an error on my side? Wondering.

This error was caused by incompatible certificates. acme.sh got the ECC certificate by default, but DSM won't recognize this (RSA type only). I had to add --keylength 2048 at the end of the --issue command line. After obtained the new certificate, I successfully --deploy it.

**Closed** 2024-08-20 03:59 UTC

**Comment by coandco** [comment] 2024-10-20 05:19
Thanks

> > My bad. I'm hitting "Unable to update certificate, got error response: {"error":{"code":5598},"success":false}." Is this an error on my side? Wondering.
> 
> This error was caused by incompatible certificates. acme.sh got the ECC certificate by default, but DSM won't recognize this (RSA type only). I had to add --keylength 2048 at the end of the --issue command line. After obtained the new certificate, I successfully --deploy it.

Thanks so much, this fixed it for me!
